### ISSUE TITLE
STRIPE required as input for secrets.update()

### ISSUE THREAD

**Issue by alundquist09** [DopplerHQ/node-sdk#18]
The STRIPE property is required as part of the `Secrets` interface. It is not possible to call `secrets.update()` without including this property.

Example code:
```
  const input = {
    config: 'dev',
    project: 'test-project',
    secrets: {
      TEST_SECRET: 'test_secret_value',
    }
  };

  const response = await sdk.secrets.update(input);
```

Resulting error:
```
Argument of type '{ config: string; project: string; secrets: { TEST_SECRET: string; }; }' is not assignable to parameter of type 'UpdateRequest'.
  Types of property 'secrets' are incompatible.
    Property 'STRIPE' is missing in type '{ TEST_SECRET: string; }' but required in type 'Secrets'.
```

Please make the STRIPE property optional.

**Comment by green2jello** [comment]
Bumping this again. Why is there a missing property of STRIPE?

**Comment by kyle-mcguire** [comment]
Hi @green2jello, this issue will be fixed in the next SDK update. It should go out sometime this week.
